#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Resolve app home and other logic...
exec "$JAVACMD" \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$GRADLE_HOME/lib/gradle-launcher-7.5.jar" \
    org.gradle.launcher.GradleMain \
    "$@"
